spring:
    application:
        name: tic-tak-tow
    datasource:
        url: jdbc:postgresql://10.0.0.2:54321/training
        username: training
        password: training
        driver-class-name: org.postgresql.Driver
    data:
        redis:
            host: 10.0.0.2
            port: 6379
    session:
        timeout: 1h

logging:
  level: 
    '[com.dedshot.game]': debug